// src/pages/Trader.jsx — v4
// Two separate sections:
//   1. MY MANUAL TRADES — user's personal portfolio from available cash
//   2. MY STRATEGIES    — auto-trader managed funds

import { useState, useEffect, useCallback } from "react";
import {
  getPortfolioOverview, getManualTrades,
  getStrategyTrades, getPortfolioTransactions,
  portfolioAcceptAgreement, portfolioAllocate, portfolioReduce,
  portfolioPause, portfolioStop,
} from "../lib/api";
import { TradeHistoryTab, TransactionHistoryTab } from "../components/TradeHistory";

const fmt    = (n, d = 2) => (+(n ?? 0)).toFixed(d);
const sign   = (n) => (+(n ?? 0)) >= 0 ? "+" : "";
const pnlCls = (n) => (+(n ?? 0)) >= 0 ? "up" : "down";
const RISK_COLOR = { LOW: "var(--green)", MEDIUM: "var(--amber)", HIGH: "var(--red)" };
const MONO = "'IBM Plex Mono', monospace";

// ── Agreement modal — stronger version with scroll gate ──────────────────────
const AGREEMENT_CLAUSES = [
  {
    title: "Virtual Money Only",
    text: "All funds on SignalBoard are VIRTUAL with no real monetary value. No real money is deposited, withdrawn, or traded at any time. Starting balance of $10,000 is simulated.",
  },
  {
    title: "Not a Financial Adviser",
    text: "SignalBoard is NOT a registered broker-dealer, investment adviser, or financial institution. Nothing on this platform constitutes financial advice, investment recommendations, or solicitation to buy or sell any real securities.",
  },
  {
    title: "Educational Purpose Only",
    text: "This platform exists solely for educational, research, and entertainment purposes. It is designed to help users understand technical analysis and trading concepts using simulated environments.",
  },
  {
    title: "No Liability",
    text: "SignalBoard, its operators, and developers accept NO liability for any real-world investment decisions made based on signals, analysis, or information presented on this platform. You use this platform entirely at your own risk.",
  },
  {
    title: "AI Signals Are Not Guarantees",
    text: "All signals are generated by AI algorithms and may be incorrect, delayed, or based on incomplete data. Past signal performance does not guarantee future results. Real markets are unpredictable.",
  },
  {
    title: "Personal Responsibility",
    text: "I accept full personal responsibility for any real investment decisions I make. I will not hold SignalBoard or its operators responsible for any real financial losses related to my real-world trading activities.",
  },
  {
    title: "No Real Trades Executed",
    text: "I understand that no real trades are executed on any exchange, brokerage, or financial market. The auto-trader operates entirely within a virtual simulation using real market data for pricing only.",
  },
];

const CONFIRM_ITEMS = [
  "I understand all funds are virtual with no real monetary value",
  "I will not make real investment decisions based on SignalBoard signals",
  "I accept that AI signals can be wrong and carry no guarantees",
  "I release SignalBoard from any liability for my real-world decisions",
];

function AgreementModal({ onAccept, loading }) {
  const [scrolled,  setScrolled]  = useState(false);
  const [checked,   setChecked]   = useState(Array(CONFIRM_ITEMS.length).fill(false));
  const [fullName,  setFullName]  = useState("");
  const allChecked = checked.every(Boolean) && scrolled && fullName.trim().length >= 2;

  function handleScroll(e) {
    const el = e.target;
    if (el.scrollHeight - el.scrollTop - el.clientHeight < 30) {
      setScrolled(true);
    }
  }

  return (
    <div className="overlay">
      <div className="modal" style={{ maxWidth: 540, maxHeight: "90vh", display: "flex", flexDirection: "column" }}>
        <div className="modal-header" style={{ flexShrink: 0 }}>
          <span style={{ fontSize: 28 }}>⚖️</span>
          <div>
            <div className="modal-title">Paper Trading Agreement</div>
            <div className="modal-sub">Read carefully — scroll to bottom to continue</div>
          </div>
        </div>
        <div style={{
          background: "#f8514912", border: "1px solid #f8514940",
          borderRadius: 8, padding: "8px 14px", margin: "0 0 12px",
          fontFamily: "var(--mono)", fontSize: 10, color: "#f85149",
          lineHeight: 1.5, flexShrink: 0,
        }}>
          🚨 IMPORTANT: SignalBoard uses VIRTUAL money only. No real funds. No real trades.
          This is a simulation platform for educational purposes.
        </div>
        <div onScroll={handleScroll} style={{
          overflowY: "auto", flex: 1,
          border: "1px solid #21262d", borderRadius: 8,
          padding: "12px 14px", marginBottom: 12,
          background: "#0d1117",
        }}>
          {AGREEMENT_CLAUSES.map((clause, i) => (
            <div key={i} style={{ marginBottom: 14 }}>
              <div style={{
                fontFamily: "var(--mono)", fontSize: 10, fontWeight: 700,
                color: "#58a6ff", marginBottom: 4,
                textTransform: "uppercase", letterSpacing: 0.5,
              }}>{i + 1}. {clause.title}</div>
              <div style={{
                fontFamily: "var(--mono)", fontSize: 10,
                color: "#8b949e", lineHeight: 1.7,
              }}>{clause.text}</div>
            </div>
          ))}
          <div style={{
            textAlign: "center", padding: "10px 0",
            fontFamily: "var(--mono)", fontSize: 9,
            color: scrolled ? "#3fb950" : "#6e7681",
          }}>
            {scrolled ? "✓ You have read the full agreement" : "↓ Scroll to bottom to continue"}
          </div>
        </div>
        <div style={{ flexShrink: 0 }}>
          {CONFIRM_ITEMS.map((text, i) => (
            <label key={i} className="check-row"
              style={{ opacity: scrolled ? 1 : 0.4, pointerEvents: scrolled ? "auto" : "none" }}
              onClick={() => scrolled && setChecked(c => c.map((v, j) => j === i ? !v : v))}>
              <div className={`check-box ${checked[i] ? "checked" : ""}`}>{checked[i] ? "✓" : ""}</div>
              <span style={{ fontSize: 11 }}>{text}</span>
            </label>
          ))}
          <div style={{ margin: "10px 0 14px" }}>
            <div style={{
              fontFamily: "var(--mono)", fontSize: 9, color: "#6e7681",
              marginBottom: 4, textTransform: "uppercase", letterSpacing: 0.5,
            }}>Type your full name to confirm</div>
            <input
              value={fullName}
              onChange={e => setFullName(e.target.value)}
              placeholder="Your full name"
              disabled={!scrolled || !checked.every(Boolean)}
              style={{
                width: "100%", padding: "8px 12px", boxSizing: "border-box",
                background: "#161b22", border: "1px solid #30363d",
                borderRadius: 6, color: "#e6edf3",
                fontFamily: "var(--mono)", fontSize: 12,
                opacity: scrolled && checked.every(Boolean) ? 1 : 0.4,
              }}
            />
          </div>
          <button className="btn btn-primary"
            style={{ width: "100%", opacity: allChecked ? 1 : 0.35 }}
            disabled={!allChecked || loading}
            onClick={onAccept}>
            {loading ? "Saving…" : "I Agree — Enter Auto-Trader"}
          </button>
          <div style={{
            textAlign: "center", marginTop: 8,
            fontFamily: "var(--mono)", fontSize: 9, color: "#6e7681",
          }}>
            This agreement is stored with your account · Virtual trading only
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Confirm modal ─────────────────────────────────────────────────────────────
function ConfirmModal({ title, description, warning, details, confirmLabel,
  confirmClass = "btn-primary", onConfirm, onCancel, loading, children }) {
  return (
    <div className="overlay">
      <div className="modal" style={{ maxWidth: 460 }}>
        <div className="modal-title" style={{ marginBottom: 6 }}>{title}</div>
        <div className="hint" style={{ marginBottom: 14, lineHeight: 1.6 }}>{description}</div>
        {details && (
          <div style={{ background: "var(--bg2)", border: "1px solid var(--border)",
            borderRadius: 8, padding: "10px 14px", marginBottom: 14 }}>
            {details.map(([l, v]) => (
              <div key={l} style={{ display: "flex", justifyContent: "space-between", marginBottom: 4 }}>
                <span className="hint">{l}</span>
                <span className="mono" style={{ fontSize: 12 }}>{v}</span>
              </div>
            ))}
          </div>
        )}
        {children}
        {warning && (
          <div style={{ background: "#f8514912", border: "1px solid #f8514940",
            borderRadius: 8, padding: "8px 14px", marginBottom: 14,
            fontSize: 12, color: "var(--red)", lineHeight: 1.5 }}>
            ⚠ {warning}
          </div>
        )}
        <div style={{ fontSize: 10, color: "var(--text3)", fontFamily: "var(--mono)", marginBottom: 14 }}>
          📊 Virtual money only — no real funds involved
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button className="btn" style={{ flex: 1 }} onClick={onCancel} disabled={loading}>Cancel</button>
          <button
            className="btn"
            style={{
              flex: 1, opacity: loading ? 0.6 : 1,
              ...(confirmClass === "btn-primary" ? { background: "linear-gradient(135deg,#1f6feb,#388bfd)", borderColor: "transparent", color: "#fff", fontWeight: 700 } : {}),
              ...(confirmClass === "btn-danger"  ? { background: "#f8514915", border: "1px solid #f8514950", color: "var(--red)", fontWeight: 700 } : {}),
            }}
            onClick={onConfirm} disabled={loading}>
            {loading ? "Processing…" : confirmLabel}
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Allocate modal ────────────────────────────────────────────────────────────
function AllocateModal({ cfg, allocation, availableCash, onConfirm, onCancel, loading }) {
  const [amount, setAmount] = useState("");
  const numVal    = parseFloat(amount) || 0;
  const afterCash = availableCash - numVal;
  const valid     = numVal > 0 && numVal <= availableCash;
  return (
    <ConfirmModal
      title={allocation ? `Add More to ${cfg.label}` : `Start ${cfg.label}`}
      description={allocation
        ? `Add more virtual funds to your ${cfg.label} strategy.`
        : `Allocate virtual funds to start the ${cfg.label} strategy.`}
      details={[
        ["Strategy",         cfg.label],
        ["Risk Level",       cfg.risk_level],
        ["Position Size",    `${(cfg.position_pct * 100).toFixed(0)}% per trade`],
        ["Stop-Loss",        `${cfg.stop_loss_default}%`],
        ["Trades in",        cfg.universe?.join(", ")],
        ...(allocation ? [["Current Allocation", `$${fmt(allocation.allocated)}`]] : []),
        ["Available Cash",   `$${fmt(availableCash)}`],
        ["After Allocation", numVal > 0 ? `$${fmt(afterCash)}` : "—"],
      ]}
      confirmLabel={allocation ? "Add Funds" : "▶ Start Strategy"}
      onConfirm={() => valid && onConfirm(numVal)}
      onCancel={onCancel} loading={loading}
    >
      <div style={{ marginBottom: 14 }}>
        <div className="stat-label" style={{ marginBottom: 8 }}>AMOUNT TO ALLOCATE</div>
        <div style={{ display: "flex", gap: 6, marginBottom: 8 }}>
          {[100, 500, 1000, 2500].map(v => (
            <button key={v} className="btn"
              style={{ flex: 1, fontSize: 11, opacity: v > availableCash ? 0.3 : 1 }}
              disabled={v > availableCash} onClick={() => setAmount(String(v))}>
              ${v}
            </button>
          ))}
        </div>
        <input className="input" type="number" min={1} max={availableCash}
          placeholder={`Max $${fmt(availableCash)}`}
          value={amount} onChange={e => setAmount(e.target.value)} autoFocus />
        {numVal > availableCash && (
          <div style={{ color: "var(--red)", fontSize: 11, marginTop: 4 }}>
            Exceeds available cash by ${fmt(numVal - availableCash)}
          </div>
        )}
      </div>
    </ConfirmModal>
  );
}

// ── Reduce modal ──────────────────────────────────────────────────────────────
function ReduceModal({ cfg, allocation, onConfirm, onCancel, loading }) {
  const [amount, setAmount] = useState("");
  const numVal  = parseFloat(amount) || 0;
  const idle    = allocation?.cash_in_strategy ?? 0;
  const valid   = numVal > 0 && numVal <= idle;
  return (
    <ConfirmModal
      title={`Reduce ${cfg.label} Allocation`}
      description="Return idle (uninvested) cash from this strategy back to your available cash."
      details={[
        ["Idle Cash Available", `$${fmt(idle)}`],
        ["Currently Invested",  `$${fmt(allocation?.invested ?? 0)}`],
        ["After Reduction",     numVal > 0 ? `$${fmt(idle - numVal)} remaining idle` : "—"],
      ]}
      confirmLabel="Return to Available Cash"
      onConfirm={() => valid && onConfirm(numVal)}
      onCancel={onCancel} loading={loading}
    >
      <div style={{ marginBottom: 14 }}>
        <div className="stat-label" style={{ marginBottom: 8 }}>AMOUNT TO RETURN</div>
        <input className="input" type="number" min={1} max={idle}
          placeholder={`Max $${fmt(idle)} idle`}
          value={amount} onChange={e => setAmount(e.target.value)} autoFocus />
        {numVal > idle && (
          <div style={{ color: "var(--red)", fontSize: 11, marginTop: 4 }}>
            Only ${fmt(idle)} idle cash available
          </div>
        )}
      </div>
    </ConfirmModal>
  );
}

// ── Manual position card ──────────────────────────────────────────────────────
function ManualPositionCard({ pos, prices = {} }) {
  const priceData = prices[pos.symbol];
  const livePrice = (typeof priceData === 'object' ? priceData?.price : priceData)
                    ?? pos.current_price ?? pos.avg_buy_price ?? 0;
  const shares    = pos.shares ?? 0;
  const abp       = pos.avg_buy_price ?? pos.buy_price ?? 0;
  const liveValue = livePrice * shares;
  const pnl       = abp > 0 ? liveValue - (abp * shares) : (pos.unrealized_pnl ?? 0);
  const pnlPct    = abp > 0 ? ((livePrice - abp) / abp) * 100 : (pos.unrealized_pnl_pct ?? 0);
  return (
    <div className="position-card fade-in">
      <div className="position-header">
        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          <span className="position-symbol">{pos.symbol}</span>
          <span className="badge badge-dim">MANUAL</span>
        </div>
        <div className="position-pnl">
          <div className={`main ${pnlCls(pnl)}`}>{sign(pnl)}${fmt(Math.abs(pnl))}</div>
          <div className={`sub ${pnlCls(pnlPct)}`}>{sign(pnlPct)}{fmt(pnlPct)}%</div>
        </div>
      </div>
      <div className="stat-grid">
        {[["Shares", fmt(pos.shares, 4)], ["Avg Buy", `$${fmt(pos.avg_buy_price)}`],
          ["Now", `$${fmt(livePrice)}`], ["Value", `$${fmt(liveValue)}`]
        ].map(([l, v]) => (
          <div key={l} className="stat-item">
            <span className="stat-label">{l}</span>
            <span className="stat-value">{v}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Strategy position card — Option C (all 3 sell triggers visible) ───────────
function StrategyPositionCard({ pos, prices = {} }) {
  // Live price from WebSocket
  const priceData    = prices[pos.symbol];
  const livePrice    = (typeof priceData === 'object' ? priceData?.price : priceData)
                       ?? pos.current_price ?? pos.buy_price ?? 0;
  const shares       = pos.shares ?? 0;
  const bp           = pos.buy_price ?? 0;
  const liveValue    = livePrice * shares;
  const pnl          = bp > 0 ? liveValue - (bp * shares) : (pos.unrealized_pnl ?? 0);
  const pnlPct       = bp > 0 ? ((livePrice - bp) / bp) * 100 : (pos.unrealized_pnl_pct ?? 0);

  // Trailing stop values
  // If trailing_high missing (old position before fix), use max of live price and buy price
  const trailingHigh = pos.trailing_high ?? Math.max(livePrice, bp);
  const slPct        = pos.stop_loss_pct ?? 8;
  const trailingStop = +(trailingHigh * (1 - slPct / 100)).toFixed(2);
  const hardStop     = pos.stop_loss_price ?? +(bp * (1 - slPct / 100)).toFixed(2);
  const targetPrice  = pos.target_price ?? 0;

  // Progress bar — from hard stop to trailing high
  const barRange = trailingHigh - hardStop;
  const barPct   = barRange > 0
    ? Math.max(0, Math.min(100, ((livePrice - hardStop) / barRange) * 100))
    : 100;

  // Color based on distance from trailing stop
  const distFromTrail = trailingHigh > 0
    ? ((livePrice - trailingStop) / trailingHigh) * 100 : 100;
  const barColor = distFromTrail < 2
    ? "var(--red)" : distFromTrail < 5
    ? "var(--amber)" : "var(--green)";

  // Which priority is closest to triggering
  const nextTrigger = livePrice <= hardStop ? "hard_stop"
    : livePrice <= trailingStop ? "trailing"
    : "none";

  return (
    <div className="position-card fade-in">
      {/* Header — symbol + P&L */}
      <div className="position-header">
        <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}>
          <span className="position-symbol">{pos.symbol}</span>
          <span className="badge badge-dim">{pos.signal_confidence || "AUTO"}</span>
          {trailingHigh > bp && (
            <span style={{
              fontFamily: MONO, fontSize: 9, color: "#3fb950",
              background: "#3fb95015", border: "1px solid #3fb95030",
              borderRadius: 4, padding: "1px 6px",
            }}>↑ trailing</span>
          )}
        </div>
        <div className="position-pnl">
          <div className={`main ${pnlCls(pnl)}`}>{sign(pnl)}${fmt(Math.abs(pnl))}</div>
          <div className={`sub ${pnlCls(pnlPct)}`}>{sign(pnlPct)}{fmt(pnlPct)}%</div>
        </div>
      </div>

      {/* Stats */}
      <div className="stat-grid">
        {[
          ["Shares",  fmt(shares, 4)],
          ["Bought",  `$${fmt(bp)}`],
          ["Now",     `$${fmt(livePrice)}`],
          ["Peak",    `$${fmt(trailingHigh)}`],
          ["Value",   `$${fmt(liveValue)}`],
          ...(targetPrice > 0 ? [["Target", `$${fmt(targetPrice)}`]] : []),
        ].map(([l, v]) => (
          <div key={l} className="stat-item">
            <span className="stat-label">{l}</span>
            <span className="stat-value" style={{
              color: l === "Peak" ? "#3fb950"
                : l === "Target" ? "#58a6ff" : undefined,
            }}>{v}</span>
          </div>
        ))}
      </div>

      {/* Price bar — hard stop → live → trailing high */}
      <div className="sl-bar-wrap" style={{ marginTop: 10 }}>
        <div className="sl-bar-labels" style={{ display: "flex", justifyContent: "space-between", marginBottom: 3 }}>
          <span style={{ fontFamily: MONO, fontSize: 9, color: "#f85149" }}>Hard ${fmt(hardStop)}</span>
          <span style={{ fontFamily: MONO, fontSize: 9, color: "#e3b341" }}>Trail ${fmt(trailingStop)}</span>
          <span style={{ fontFamily: MONO, fontSize: 9, color: "#3fb950" }}>Peak ${fmt(trailingHigh)}</span>
        </div>
        <div className="sl-bar-track">
          <div className="sl-bar-fill" style={{
            width: `${barPct}%`,
            background: barColor,
            transition: "width 0.5s, background 0.5s",
          }} />
        </div>
      </div>

      {/* 3 sell triggers */}
      <div style={{
        marginTop: 10, padding: "8px 10px",
        background: "#0d1117", borderRadius: 8,
        border: "1px solid #21262d",
      }}>
        <div style={{
          fontFamily: MONO, fontSize: 8, color: "#6e7681",
          letterSpacing: 1, marginBottom: 6, textTransform: "uppercase",
        }}>Sell triggers</div>
        <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>

          {/* ① SELL signal */}
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <span style={{
              fontFamily: MONO, fontSize: 9, fontWeight: 700,
              color: "#f85149", background: "#f8514915",
              border: "1px solid #f8514930",
              borderRadius: 4, padding: "1px 6px",
            }}>①</span>
            <span style={{ fontFamily: MONO, fontSize: 9, color: "#8b949e", flex: 1 }}>
              AI SELL signal (HIGH confidence)
            </span>
            <span style={{ fontFamily: MONO, fontSize: 9, color: "#6e7681" }}>immediate</span>
          </div>

          {/* ② Trailing stop */}
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <span style={{
              fontFamily: MONO, fontSize: 9, fontWeight: 700,
              color: "#e3b341", background: "#e3b34115",
              border: "1px solid #e3b34130",
              borderRadius: 4, padding: "1px 6px",
            }}>②</span>
            <span style={{ fontFamily: MONO, fontSize: 9, color: "#8b949e", flex: 1 }}>
              Trailing stop ${fmt(trailingStop)}
              <span style={{ color: "#6e7681" }}> ({slPct}% below peak ${fmt(trailingHigh)})</span>
            </span>
            <span style={{
              fontFamily: MONO, fontSize: 9,
              color: nextTrigger === "trailing" ? "#e3b341" : "#6e7681",
            }}>
              {nextTrigger === "trailing" ? "⚡ active" : `↓ $${fmt(livePrice - trailingStop)}`}
            </span>
          </div>

          {/* ③ Hard stop */}
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <span style={{
              fontFamily: MONO, fontSize: 9, fontWeight: 700,
              color: "#6e7681", background: "#6e767115",
              border: "1px solid #6e767130",
              borderRadius: 4, padding: "1px 6px",
            }}>③</span>
            <span style={{ fontFamily: MONO, fontSize: 9, color: "#8b949e", flex: 1 }}>
              Hard stop-loss ${fmt(hardStop)}
              <span style={{ color: "#6e7681" }}> ({slPct}% below buy ${fmt(bp)})</span>
            </span>
            <span style={{
              fontFamily: MONO, fontSize: 9,
              color: nextTrigger === "hard_stop" ? "#f85149" : "#6e7681",
            }}>
              {nextTrigger === "hard_stop" ? "⚡ active" : `↓ $${fmt(livePrice - hardStop)}`}
            </span>
          </div>

        </div>
      </div>
    </div>
  );
}

// ── Strategy card ─────────────────────────────────────────────────────────────
function StrategyCard({ sk, cfg, allocation, onAction, selected, onSelect }) {
  const isAllocated = !!allocation;
  const isPaused    = allocation?.is_paused ?? false;
  const pnl         = allocation?.pnl ?? 0;
  const pnlPct      = allocation?.pnl_pct ?? 0;

  return (
    <div
      className={`strategy-card ${selected === sk ? "selected" : ""}`}
      onClick={() => isAllocated && onSelect(sk)}
      style={{ borderColor: isAllocated ? (isPaused ? "var(--amber)" : "var(--blue)") : "var(--border)", cursor: isAllocated ? "pointer" : "default" }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6 }}>
        <div className="name" style={{ color: isAllocated ? "var(--text1)" : "var(--text2)" }}>
          {cfg.label}
        </div>
        <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
          {isAllocated && (
            <span style={{ fontSize: 10, fontFamily: "var(--mono)", padding: "2px 8px", borderRadius: 4,
              background: isPaused ? "#e3b34120" : "#0fffa315",
              color: isPaused ? "var(--amber)" : "var(--signal-buy)",
              border: `1px solid ${isPaused ? "#e3b34140" : "#0fffa340"}` }}>
              {isPaused ? "⏸ PAUSED" : "● ACTIVE"}
            </span>
          )}
          <span className="badge" style={{
            background: `${RISK_COLOR[cfg.risk_level]}15`,
            color: RISK_COLOR[cfg.risk_level],
            border: `1px solid ${RISK_COLOR[cfg.risk_level]}40`
          }}>{cfg.risk_level}</span>
        </div>
      </div>

      <div className="desc">{cfg.description}</div>

      {isAllocated ? (
        <>
          <div className="stat-grid" style={{ marginBottom: 10 }}>
            {[
              ["Allocated",  `$${fmt(allocation.allocated)}`],
              ["Idle Cash",  `$${fmt(allocation.cash_in_strategy)}`],
              ["Invested",   `$${fmt(allocation.invested)}`],
              ["P&L",        `${sign(pnl)}$${fmt(Math.abs(pnl))} (${sign(pnlPct)}${fmt(pnlPct)}%)`],
            ].map(([l, v]) => (
              <div key={l} className="stat-item">
                <span className="stat-label">{l}</span>
                <span className={`stat-value ${l === "P&L" ? pnlCls(pnl) : ""}`}>{v}</span>
              </div>
            ))}
          </div>
          <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
            <button className="btn" style={{ fontSize: 11 }}
              onClick={e => { e.stopPropagation(); onAction("allocate", sk); }}>＋ Add</button>
            <button className="btn" style={{ fontSize: 11 }}
              onClick={e => { e.stopPropagation(); onAction("reduce", sk); }}>－ Reduce</button>
            <button className="btn" style={{ fontSize: 11 }}
              onClick={e => { e.stopPropagation(); onAction("pause", sk); }}>
              {isPaused ? "▶ Resume" : "⏸ Pause"}
            </button>
            <button className="btn" style={{ fontSize: 11, color: "var(--red)" }}
              onClick={e => { e.stopPropagation(); onAction("stop", sk); }}>■ Stop</button>
          </div>
          <div className="hint" style={{ marginTop: 8, fontSize: 10 }}>
            Click card to view positions & trades ↓
          </div>
        </>
      ) : (
        <>
          <div className="stat-grid" style={{ marginBottom: 10 }}>
            {[["Position", `${(cfg.position_pct*100).toFixed(0)}%`],
              ["Stop-Loss", `${cfg.stop_loss_default}%`],
              ["Min Signal", cfg.min_confidence],
              ["Reserve", `${(cfg.cash_reserve_pct*100).toFixed(0)}%`]].map(([l, v]) => (
              <div key={l} className="stat-item">
                <span className="stat-label">{l}</span>
                <span className="stat-value">{v}</span>
              </div>
            ))}
          </div>
          <button className="btn btn-primary" style={{ width: "100%", fontSize: 12 }}
            onClick={e => { e.stopPropagation(); onAction("allocate", sk); }}>
            ▶ Allocate Funds to Start
          </button>
        </>
      )}
      <div className="universe" style={{ marginTop: 8 }}>{cfg.universe?.join(" · ")}</div>
    </div>
  );
}

// ── Main ──────────────────────────────────────────────────────────────────────
export default function Trader({ onPortfolioUpdate, prices = {} }) {
  const [overview,      setOverview]      = useState(null);
  const [manualTrades,  setManualTrades]  = useState([]);
  const [stratTrades,   setStratTrades]   = useState([]);
  const [transactions,  setTransactions]  = useState([]);
  const [loading,       setLoading]       = useState(true);
  const [acting,        setActing]        = useState(false);
  const [error,         setError]         = useState(null);
  const [toast,         setToast]         = useState(null);
  const [modal,         setModal]         = useState(null);
  const [selectedSk,    setSelectedSk]    = useState(null);
  const [stratTab,      setStratTab]      = useState("positions");
  const [mainTab,       setMainTab]       = useState("strategies");

  const summary    = overview?.summary    ?? {};
  const strategies = overview?.strategies ?? {};
  const manual     = overview?.manual     ?? {};

  const showToast = (msg, type = "ok") => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 3500);
  };

  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const ov = await getPortfolioOverview();
      setOverview(ov);
      onPortfolioUpdate?.(ov.summary);
    } catch {
      setError("Could not load portfolio — is the backend running?");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  useEffect(() => {
    if (!selectedSk) return;
    getStrategyTrades(selectedSk).then(d => setStratTrades(d.trades ?? [])).catch(() => {});
    getPortfolioTransactions().then(d => setTransactions(d.transactions ?? [])).catch(() => {});
  }, [selectedSk]);

  useEffect(() => {
    if (mainTab === "manual") {
      getManualTrades().then(d => setManualTrades(d.trades ?? [])).catch(() => {});
    }
  }, [mainTab]);

  const act = async (fn, successMsg) => {
    setActing(true);
    try { await fn(); await load(); showToast(successMsg); }
    catch (e) { showToast(e.message || "Action failed", "err"); }
    finally { setActing(false); setModal(null); }
  };

  const handleAgreement = () => act(portfolioAcceptAgreement, "Agreement accepted — welcome!");
  const handleAllocate  = (amount) => act(
    () => portfolioAllocate(modal.sk, amount),
    `$${amount.toLocaleString()} allocated to ${strategies[modal.sk]?.config?.label}`);
  const handleReduce    = (amount) => act(
    () => portfolioReduce(modal.sk, amount),
    `$${amount.toLocaleString()} returned to available cash`);
  const handlePause     = () => {
    const paused = !(strategies[modal.sk]?.allocation?.is_paused ?? false);
    act(() => portfolioPause(modal.sk, paused),
      paused ? `${strategies[modal.sk]?.config?.label} paused`
             : `${strategies[modal.sk]?.config?.label} resumed`);
  };
  const handleStop      = () => act(
    () => portfolioStop(modal.sk),
    `${strategies[modal.sk]?.config?.label} stopped — funds returned to available cash`);

  if (loading) return <div className="hint mono" style={{ padding: 40, textAlign: "center" }}>Loading portfolio…</div>;
  if (error)   return (
    <div className="card empty-state">
      <div style={{ fontSize: 28, marginBottom: 8 }}>⚠️</div>
      {error}
      <button className="btn btn-primary" style={{ marginTop: 12 }} onClick={load}>↻ Retry</button>
    </div>
  );

  const selectedData  = selectedSk ? strategies[selectedSk] : null;
  const selectedCfg   = selectedData?.config ?? {};
  const selectedAlloc = selectedData?.allocation ?? null;

  return (
    <div style={{ maxWidth: 1100, margin: "0 auto" }}>

      {!summary.agreement_accepted && <AgreementModal onAccept={handleAgreement} loading={acting} />}

      {modal?.type === "allocate" && (
        <AllocateModal
          cfg={strategies[modal.sk]?.config ?? {}}
          allocation={strategies[modal.sk]?.allocation ?? null}
          availableCash={summary.available_cash ?? 0}
          onConfirm={handleAllocate} onCancel={() => setModal(null)} loading={acting}
        />
      )}
      {modal?.type === "reduce" && (
        <ReduceModal
          cfg={strategies[modal.sk]?.config ?? {}}
          allocation={strategies[modal.sk]?.allocation ?? null}
          onConfirm={handleReduce} onCancel={() => setModal(null)} loading={acting}
        />
      )}
      {modal?.type === "pause" && (
        <ConfirmModal
          title={strategies[modal.sk]?.allocation?.is_paused
            ? `Resume ${strategies[modal.sk]?.config?.label}`
            : `Pause ${strategies[modal.sk]?.config?.label}`}
          description={strategies[modal.sk]?.allocation?.is_paused
            ? "Resume auto-trading. The strategy will begin opening new positions on the next qualifying signal."
            : "Pause auto-trading. Your open positions stay open and P&L keeps updating. No new trades will be placed."}
          details={[
            ["Open Positions", String((strategies[modal.sk]?.positions ?? []).length)],
            ["Invested",       `$${fmt(strategies[modal.sk]?.allocation?.invested ?? 0)}`],
            ["Idle Cash",      `$${fmt(strategies[modal.sk]?.allocation?.cash_in_strategy ?? 0)}`],
          ]}
          confirmLabel={strategies[modal.sk]?.allocation?.is_paused ? "▶ Resume" : "⏸ Pause"}
          onConfirm={handlePause} onCancel={() => setModal(null)} loading={acting}
        />
      )}
      {modal?.type === "stop" && (
        <ConfirmModal
          title={`Stop ${strategies[modal.sk]?.config?.label}`}
          description="This will immediately close ALL open positions at current market prices and return all funds to your available cash."
          warning="This action cannot be undone. All positions will be closed at current market price."
          details={[
            ["Open Positions",  String((strategies[modal.sk]?.positions ?? []).length)],
            ["Total to Return", `$${fmt(strategies[modal.sk]?.allocation?.total_value ?? 0)}`],
          ]}
          confirmLabel="■ Stop & Return All Funds"
          confirmClass="btn-danger"
          onConfirm={handleStop} onCancel={() => setModal(null)} loading={acting}
        />
      )}

      {toast && <div className={`toast ${toast.type}`}>{toast.msg}</div>}

      <div className="paper-banner">
        📊 Paper Portfolio — Virtual Money Only · No real funds involved · All figures simulated
      </div>

      <div className="summary-grid" style={{ marginBottom: 20 }}>
        {[
          { label: "Your Portfolio Value", value: `$${fmt(summary.total_value)}`, cls: "up" },
          { label: "Available Cash",       value: `$${fmt(summary.available_cash)}`, cls: "" },
          { label: "Manual Positions",     value: `$${fmt(summary.manual_value ?? 0)}`, cls: "muted" },
          { label: "In Strategies",        value: `$${fmt(summary.strategy_value ?? 0)}`, cls: "muted" },
          { label: "Total Deposited",      value: `$${fmt(summary.total_deposited)}`, cls: "muted" },
        ].map(({ label, value, cls }) => (
          <div key={label} className="summary-card">
            <div className="stat-label">{label}</div>
            <div className={`stat-value ${cls}`}>{value}</div>
          </div>
        ))}
      </div>

      <div className="sub-tabs" style={{ marginBottom: 20 }}>
        {[["strategies", "🤖 My Strategies"], ["manual", "📈 My Manual Trades"]].map(([id, label]) => (
          <button key={id} className={`sub-tab ${mainTab === id ? "active" : ""}`}
            style={{ fontSize: 13, padding: "10px 20px" }}
            onClick={() => { setMainTab(id); setSelectedSk(null); }}>
            {label}
          </button>
        ))}
      </div>

      {mainTab === "strategies" && (
        <div>
          <div className="hint" style={{ marginBottom: 14 }}>
            Allocate virtual funds to a strategy and the auto-trader manages everything inside —
            buys, sells, and stop-losses. Think of each strategy as a fund you invest in.
          </div>
          <div className="strategy-grid">
            {Object.entries(strategies).map(([sk, data]) => (
              <StrategyCard
                key={sk} sk={sk}
                cfg={data.config}
                allocation={data.allocation}
                onAction={(type, key) => setModal({ type, sk: key })}
                selected={selectedSk}
                onSelect={setSelectedSk}
              />
            ))}
          </div>

          {selectedSk && selectedAlloc && (
            <div className="card" style={{ marginTop: 16 }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}>
                <div>
                  <div style={{ fontWeight: 700, fontSize: 16 }}>{selectedCfg.label}</div>
                  <div className="hint" style={{ marginTop: 2 }}>
                    ${fmt(selectedAlloc.allocated)} allocated ·{" "}
                    <span className={pnlCls(selectedAlloc.pnl ?? 0)}>
                      {sign(selectedAlloc.pnl ?? 0)}${fmt(Math.abs(selectedAlloc.pnl ?? 0))} P&L
                    </span>
                  </div>
                </div>
                <button className="hint"
                  style={{ background: "none", border: "none", cursor: "pointer", fontSize: 18 }}
                  onClick={() => setSelectedSk(null)}>✕</button>
              </div>
              <div className="sub-tabs" style={{ marginBottom: 14 }}>
                {["positions", "trades", "transactions"].map(t => (
                  <button key={t} className={`sub-tab ${stratTab === t ? "active" : ""}`}
                    onClick={() => setStratTab(t)}>{t}</button>
                ))}
              </div>
              {stratTab === "positions" && (
                <>
                  {/* Open positions */}
                  {(selectedData?.positions ?? []).length === 0 ? (
                    <div className="empty-state" style={{ marginBottom: 16 }}>
                      No open positions in {selectedCfg.label}.
                    </div>
                  ) : (
                    (selectedData?.positions ?? []).map(p => (
                      <StrategyPositionCard key={`${p.symbol}_${p.strategy_key}`} pos={p} prices={prices} />
                    ))
                  )}
                  {/* Closed positions history */}
                  {stratTrades.filter(t => t.action === "SELL").length > 0 && (
                    <div style={{ marginTop: 16 }}>
                      <div className="stat-label" style={{ marginBottom: 10 }}>
                        CLOSED POSITIONS — {stratTrades.filter(t => t.action === "SELL").length} trades
                      </div>
                      {stratTrades.filter(t => t.action === "SELL").slice(0, 10).map((t, i) => (
                        <div key={i} style={{
                          background: "var(--bg2)", border: "1px solid var(--border)",
                          borderRadius: 8, padding: "10px 14px", marginBottom: 8,
                          display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap",
                        }}>
                          <span style={{
                            fontFamily: "var(--mono)", fontSize: 10, fontWeight: 700,
                            background: "#f8514915", border: "1px solid #f8514940",
                            borderRadius: 4, padding: "1px 8px", color: "var(--red)", flexShrink: 0,
                          }}>CLOSED</span>
                          <div style={{ flex: 1, minWidth: 80 }}>
                            <div style={{ fontFamily: "var(--mono)", fontSize: 14, fontWeight: 700, color: "var(--text1)" }}>
                              {t.symbol}
                            </div>
                            <div style={{ fontFamily: "var(--mono)", fontSize: 9, color: "var(--text3)", marginTop: 2 }}>
                              {t.trigger === "trailing_stop" ? "② Trailing stop" :
                               t.trigger === "hard_stop"     ? "③ Hard stop-loss" :
                               t.trigger === "sell_signal"   ? "① SELL signal" :
                               t.trigger || "auto"}
                              {" · "}{new Date(t.timestamp).toLocaleDateString()}
                            </div>
                          </div>
                          <div style={{ textAlign: "right" }}>
                            <div style={{ fontFamily: "var(--mono)", fontSize: 9, color: "var(--text3)" }}>SOLD @</div>
                            <div style={{ fontFamily: "var(--mono)", fontSize: 13, fontWeight: 700, color: "var(--text1)" }}>
                              ${fmt(t.price)}
                            </div>
                          </div>
                          <div style={{ textAlign: "right" }}>
                            <div style={{ fontFamily: "var(--mono)", fontSize: 9, color: "var(--text3)" }}>SHARES</div>
                            <div style={{ fontFamily: "var(--mono)", fontSize: 12, color: "var(--text1)" }}>
                              {fmt(t.shares, 4)}
                            </div>
                          </div>
                          <div style={{ textAlign: "right" }}>
                            <div style={{ fontFamily: "var(--mono)", fontSize: 15, fontWeight: 700,
                              color: (t.pnl ?? 0) >= 0 ? "var(--green)" : "var(--red)" }}>
                              {sign(t.pnl ?? 0)}${fmt(Math.abs(t.pnl ?? 0))}
                            </div>
                            <div style={{ fontFamily: "var(--mono)", fontSize: 9,
                              color: (t.pnl_pct ?? 0) >= 0 ? "var(--green)" : "var(--red)" }}>
                              {sign(t.pnl_pct ?? 0)}{fmt(Math.abs(t.pnl_pct ?? 0))}%
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </>
              )}
              {stratTab === "trades" && <TradeHistoryTab trades={stratTrades} />}
              {stratTab === "transactions" && (
                <TransactionHistoryTab
                  transactions={transactions.filter(t => t.strategy_key === selectedSk || !t.strategy_key)}
                  wallet={summary}
                />
              )}
            </div>
          )}

          {Object.values(strategies).every(s => !s.is_allocated) && !loading && (
            <div className="card empty-state" style={{ marginTop: 16 }}>
              <div style={{ fontSize: 32, marginBottom: 8 }}>🚀</div>
              <div style={{ marginBottom: 8 }}>
                You have <strong>${fmt(summary.available_cash)}</strong> available.
              </div>
              <div className="hint">
                Click <strong>▶ Allocate Funds to Start</strong> on any strategy above to begin auto-trading.
              </div>
            </div>
          )}
        </div>
      )}

      {mainTab === "manual" && (
        <div>
          <div className="hint" style={{ marginBottom: 14 }}>
            Your personal trades — bought directly from available cash. The auto-trader never
            touches these. Buy any stock from Live Prices using the Portfolio tab.
          </div>
          {(manual.positions ?? []).length === 0 ? (
            <div className="card empty-state" style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 28, marginBottom: 8 }}>📈</div>
              <div style={{ marginBottom: 8 }}>No manual positions yet.</div>
              <div className="hint">
                Go to <strong>Live Prices → Portfolio tab</strong> on any stock to place a manual buy.
              </div>
            </div>
          ) : (
            <div style={{ marginBottom: 20 }}>
              <div className="stat-label" style={{ marginBottom: 12 }}>
                OPEN POSITIONS — {(manual.positions ?? []).length} stocks ·
                Total value: ${fmt(manual.total_value)} ·
                <span className={pnlCls(manual.total_pnl)}>
                  {" "}{sign(manual.total_pnl)}${fmt(Math.abs(manual.total_pnl ?? 0))} P&L
                </span>
              </div>
              {(manual.positions ?? []).map(p => <ManualPositionCard key={p.symbol} pos={p} prices={prices} />)}
            </div>
          )}
          <div className="stat-label" style={{ marginBottom: 12 }}>TRADE HISTORY</div>
          <TradeHistoryTab trades={manualTrades} />
        </div>
      )}

    </div>
  );
}