// src/components/TermsModal.jsx
// Scroll-to-bottom modal — agree button enables only after user scrolls to end

import { useState, useRef, useEffect } from "react";

export default function TermsModal({ onAccept, onClose }) {
  const [scrolled, setScrolled] = useState(false);
  const bodyRef = useRef(null);

  const handleScroll = () => {
    const el = bodyRef.current;
    if (!el) return;
    const atBottom = el.scrollTop + el.clientHeight >= el.scrollHeight - 20;
    if (atBottom) setScrolled(true);
  };

  useEffect(() => {
    const el = bodyRef.current;
    if (el) el.addEventListener("scroll", handleScroll);
    return () => el?.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <div style={s.overlay}>
      <div style={s.modal}>
        <div style={s.header}>
          <h2 style={s.title}>Terms of Use & Privacy Policy</h2>
          <button style={s.close} onClick={onClose}>✕</button>
        </div>

        <div style={s.body} ref={bodyRef}>
          <h3 style={s.h3}>1. Service Description</h3>
          <p style={s.p}>SignalBoard is an AI-powered stock signal platform providing BUY/HOLD/SELL signals generated by artificial intelligence. The platform includes a paper trading simulator that uses virtual money only.</p>

          <h3 style={s.h3}>2. Paper Trading Disclaimer ⚠️</h3>
          <p style={s.p}>ALL funds on SignalBoard are VIRTUAL and have ZERO real monetary value. No real trades are executed on any stock exchange. All "investments", "returns", "profits", and "losses" are entirely simulated and for educational and entertainment purposes only.</p>
          <p style={s.p}>SignalBoard is NOT a registered broker-dealer, investment adviser, or financial institution. We are NOT licensed to provide investment advice. Past simulated performance does NOT guarantee future results. You CANNOT withdraw real money from this platform.</p>

          <h3 style={s.h3}>3. Eligibility</h3>
          <p style={s.p}>You must be at least 18 years old to use SignalBoard. By creating an account, you confirm you are 18 or older and have received admin approval to access the service.</p>

          <h3 style={s.h3}>4. AI Signal Disclaimer</h3>
          <p style={s.p}>AI-generated signals are for informational and educational purposes only. They do not constitute financial advice. SignalBoard accepts no liability for any real-world investment decisions made based on signals displayed on this platform. Always consult a licensed financial adviser before making real investment decisions.</p>

          <h3 style={s.h3}>5. Data & Privacy Policy</h3>
          <p style={s.p}><strong>What we collect:</strong> Your name, email address, and anonymous paper trading activity (virtual trades, simulated P&L).</p>
          <p style={s.p}><strong>How we use it:</strong> Your name and email are used only for account management and notifications. Your anonymous trading activity may be used to improve AI signal accuracy and market analysis — this data is never linked to your personal identity when used for analysis.</p>
          <p style={s.p}><strong>How we store it:</strong> All data is stored securely via Google Firebase with encryption at rest. Your personal data is never sold to third parties.</p>
          <p style={s.p}><strong>Your rights:</strong> You may request deletion of your account and all associated data at any time by contacting kotakdhruvil@gmail.com.</p>

          <h3 style={s.h3}>6. Acceptable Use</h3>
          <p style={s.p}>You agree not to: scrape or automate requests to the platform, share your account credentials, attempt to circumvent security measures, or use the service for any unlawful purpose.</p>

          <h3 style={s.h3}>7. Intellectual Property</h3>
          <p style={s.p}>AI signals, platform design, and all content are proprietary to SignalBoard. You may not reproduce, redistribute, or use signals for commercial purposes without written permission.</p>

          <h3 style={s.h3}>8. Limitation of Liability</h3>
          <p style={s.p}>SignalBoard is provided "as-is" without warranty of any kind. We accept NO liability for: any real-world financial decisions, service interruptions, data loss, or inaccuracies in AI signals. We may modify or terminate the service at any time.</p>

          <h3 style={s.h3}>9. Changes to Terms</h3>
          <p style={s.p}>We may update these terms at any time. Continued use of the platform after changes constitutes acceptance of the updated terms. You will be notified of material changes via email.</p>

          <h3 style={s.h3}>10. Contact</h3>
          <p style={s.p}>Questions about these terms? Contact us at <strong>kotakdhruvil@gmail.com</strong></p>

          <p style={{ ...s.p, marginTop:"2rem", fontSize:11, color:"#6e7681" }}>
            Version 1.0 · Effective May 25, 2026
          </p>
        </div>

        {/* Scroll hint */}
        {!scrolled && (
          <div style={s.hint}>
            ↓ Scroll to the bottom to enable agreement
          </div>
        )}

        <div style={s.footer}>
          <button style={s.btnCancel} onClick={onClose}>Cancel</button>
          <button
            style={{ ...s.btnAgree, opacity: scrolled ? 1 : 0.4, cursor: scrolled ? "pointer" : "not-allowed" }}
            onClick={() => scrolled && onAccept()}
            disabled={!scrolled}
          >
            ✓ I Have Read and Agree
          </button>
        </div>
      </div>
    </div>
  );
}

const s = {
  overlay:   { position:"fixed", inset:0, background:"rgba(0,0,0,0.75)", zIndex:1000, display:"flex", alignItems:"center", justifyContent:"center", padding:"1rem" },
  modal:     { background:"#161b22", border:"1px solid #30363d", borderRadius:12, width:"100%", maxWidth:600, maxHeight:"85vh", display:"flex", flexDirection:"column" },
  header:    { display:"flex", alignItems:"center", justifyContent:"space-between", padding:"1.25rem 1.5rem", borderBottom:"1px solid #30363d", flexShrink:0 },
  title:     { fontSize:16, fontWeight:700, color:"#e6edf3", margin:0 },
  close:     { background:"none", border:"none", color:"#8b949e", fontSize:18, cursor:"pointer", padding:0 },
  body:      { flex:1, overflowY:"auto", padding:"1.25rem 1.5rem" },
  h3:        { fontSize:14, fontWeight:600, color:"#e6edf3", margin:"1.25rem 0 0.5rem" },
  p:         { fontSize:13, color:"#8b949e", lineHeight:1.7, margin:"0 0 0.75rem" },
  hint:      { textAlign:"center", fontSize:12, color:"#f0a000", padding:"8px", background:"#f0a00010", borderTop:"1px solid #f0a00030", flexShrink:0 },
  footer:    { display:"flex", gap:8, padding:"1rem 1.5rem", borderTop:"1px solid #30363d", flexShrink:0 },
  btnCancel: { flex:1, padding:"9px", background:"transparent", border:"1px solid #30363d", borderRadius:6, color:"#8b949e", fontSize:13, cursor:"pointer" },
  btnAgree:  { flex:2, padding:"9px", background:"#238636", border:"1px solid #2ea043", borderRadius:6, color:"#fff", fontSize:13, fontWeight:600, transition:"opacity 0.2s" },
};